### PR TITLE
Chat Input Mention fixes

### LINKED ISSUE #2021: text after mention is marked as mention
See image below

### PR DESCRIPTION
**Pull request by gtalha07**
Fixes #2021. This brings up improvements and new approach in ```trigger_autocomplete``` plugin to handle generic tags styling. Moreover, adds html text support to parse mentions for composer draft state. 

See it in action:

(Mobile) ->

https://github.com/user-attachments/assets/906cc281-067c-4cf4-93d8-2a8999fb49b3

(Desktop) ->

https://github.com/user-attachments/assets/d416bd40-9c99-4530-99f7-06fe799b8333

### CODE REVIEW

File: app/lib/features/chat/utils.dart [hunk 1]
```diff
@@ -275,23 +276,103 @@ String parseEditMsg(types.Message message) {
...
       if (selectedMessageState == SelectedMessageState.edit) {
-        await chat.saveMsgDraft(text, null, 'edit', messageId);
+        await chat.saveMsgDraft(text, htmlText, 'edit', messageId);
       } else if (selectedMessageState == SelectedMessageState.replyTo) {
-        await chat.saveMsgDraft(text, null, 'reply', messageId);
+        await chat.saveMsgDraft(text, htmlText, 'reply', messageId);
       }
     } else {
-      await chat.saveMsgDraft(text, null, 'new', null);
+      await chat.saveMsgDraft(text, htmlText, 'new', null);
```
Comment (gnunicorn) [inline app/lib/features/chat/utils.dart:375]: this isn't `html` though ... this is `markdown` isn't it?

Comment (gtalha07) [reply app/lib/features/chat/utils.dart:375]: Yes it's markdown. Thanks for pointer 👍🏻 !

**Comment by gtalha07** [comment]
We can merge as it is as this'd fix user mentions tagging on user-end without any stringent bugs. Can open PR for code improvements and future compatibilities!
