### PR TITLE
Pin Creation Refactoring

### LINKED ISSUE #1620: Can't share ical file as attachment
Create a new ical with the #1617 exporter. But uploading that as an attachment to any Pin or Task fails with a non-null-error:

https://github.com/acterglobal/a3/assets/40496/ec2168a7-ff66-4c63-ad59-b7ae8dd65ea5

### PR DESCRIPTION
**Pull request by kumarpalsinh25**
**This PR contains entire pin create refactoring with new UI-UX. Here is the quick overview of the same.**

- SpaceChip Selection : Add compact view for minimum UI design
- Able to add attachments while creating Pins
- Link as attachment instead of part of Pin
- Able to add more than one link with single Pin
- fixes #1620

### Reference Video:

https://github.com/user-attachments/assets/f32ca204-568b-48bd-b991-5505b2cd40c6

### Notes:
This PR yet not contains entire refactoring of Pins Module as don't want to make huge PR which it leads to difficult to review. Here is the some of the remaining Pin Refactoring points.

- Pin Details Page Refactoring
- Backward support of Link with Attachment
- Make new Add Attachment options as Common
- UI-UX changes in Pin List
- Add support of Emoji/Icons in PIN identity

### CODE REVIEW

File: app/lib/common/models/types.dart [hunk 1]
```diff
@@ -4,7 +4,15 @@ typedef MemberInfo = ({String userId, String roomId});
...
 
-enum AttachmentType { camera, image, audio, video, location, file }
+enum AttachmentType {
+  camera,
+  image,
+  audio,
+  video,
+  location,
+  file,
+  link,
```
Comment (kumarpalsinh25) [inline app/lib/common/models/types.dart:14]: Added `link` type.

File: app/lib/common/themes/components/input_decoration_theme.dart [hunk 2]
```diff
@@ -20,6 +20,18 @@ var inputDecorationTheme = InputDecorationTheme(
     borderSide: BorderSide.none,
     borderRadius: BorderRadius.circular(12),
   ),
+  errorBorder: OutlineInputBorder(
```
Comment (kumarpalsinh25) [inline app/lib/common/themes/components/input_decoration_theme.dart:23]: Updated input decoration theme with error border color

File: app/lib/common/widgets/edit_html_description_sheet.dart [hunk 3]
```diff
@@ -69,9 +68,10 @@ class _EditHtmlDescriptionSheetState
 
   @override
   Widget build(BuildContext context) {
-    return Container(
-      padding: const EdgeInsets.symmetric(horizontal: 20.0),
+    return Padding(
+      padding: MediaQuery.of(context).viewInsets,
```
Comment (kumarpalsinh25) [inline app/lib/common/widgets/edit_html_description_sheet.dart:72]: Need to do some changes in this file to avoid keyboard overlap over the BottomSheet issue.

File: app/lib/common/widgets/spaces/select_space_form_field.dart [hunk 4]
```diff
@@ -15,6 +15,7 @@ class SelectSpaceFormField extends ConsumerWidget {
   final String? emptyText;
   final String canCheck;
   final bool mandatory;
+  final bool isCompactView;
```
Comment (kumarpalsinh25) [inline app/lib/common/widgets/spaces/select_space_form_field.dart:18]: Added flag to have support of compact view in SpaceChip and Selector UI.

File: app/lib/features/attachments/actions/handle_selected_attachments.dart [hunk 5]
```diff
@@ -0,0 +1,90 @@
+import 'dart:io';
```
Comment (kumarpalsinh25) [inline app/lib/features/attachments/actions/handle_selected_attachments.dart:1]: No changes in code expect `link` type attachment support and putted this as separate function in `Actions` folder.

File: app/lib/features/attachments/actions/handle_selected_attachments.dart [hunk 6]
```diff
@@ -0,0 +1,90 @@
...
+            .filename(fileName)
+            .size(file.lengthSync());
+        final attachmentDraft = await manager.contentDraft(fileDraft);
+        drafts.add(attachmentDraft);
+      }
+    }
+    if (attachmentType == AttachmentType.link && link != null) {
+      final attachmentDraft = await manager.linkDraft(link, title);
+      drafts.add(attachmentDraft);
+    }
```
Comment (kumarpalsinh25) [inline app/lib/features/attachments/actions/handle_selected_attachments.dart:73]: This is the only new addition in this function prior to earlier code.

File: app/lib/features/pins/widgets/pin_attachment_options.dart [hunk 7]
```diff
@@ -0,0 +1,144 @@
...
+import 'package:acter/common/models/types.dart';
+import 'package:acter/features/pins/actions/select_pin_attachments.dart';
+import 'package:acter/features/pins/actions/set_pin_description.dart';
+import 'package:acter/features/pins/actions/set_pin_links.dart';
+import 'package:acter/features/pins/providers/pins_provider.dart';
+import 'package:atlas_icons/atlas_icons.dart';
+import 'package:flutter/material.dart';
+import 'package:flutter_riverpod/flutter_riverpod.dart';
+
+class PinAttachmentOptions extends ConsumerWidget {
```
[the remark this answers is not in the document]
Comment (kumarpalsinh25) [reply app/lib/features/pins/widgets/pin_attachment_options.dart:12]: For keeping this PR minimal, only used this while create pin but latest PRs this will be used as primary add attachment action menu.

File: app/lib/features/attachments/widgets/attachment_item.dart [hunk 8]
```diff
@@ -1,41 +1,188 @@
...
+            ? () => openRedactContentDialog(
+                  context,
+                  eventId: eventId,
+                  roomId: roomId,
+                  title: L10n.of(context).deleteAttachment,
+                  description: L10n.of(context)
+                      .areYouSureYouWantToRemoveAttachmentFromPin,
+                  isSpace: true,
+                )
+            : null,
```
Comment (gnunicorn) [inline app/lib/features/attachments/widgets/attachment_item.dart:69]: long press will delete? that is not really what we usually have, where long-press is some form of select-to-copy ...

File: app/lib/features/attachments/widgets/attachment_item.dart [hunk 9]
```diff
@@ -1,41 +1,188 @@
...
+            ),
+            icon: const Icon(Atlas.download_arrow_down),
+          ),
+        ),
+      ),
+    );
+  }
+
+  Widget title(AttachmentType attachmentType) {
+    final msgContent = attachment.msgContent();
```
Comment (gnunicorn) [inline app/lib/features/attachments/widgets/attachment_item.dart:89]: there is also `final title = attachment.name()` . I think this is what you want to use and why you said that the title attributed isn't coming through. It is new but the thing you want to use!

File: app/lib/features/attachments/widgets/attachment_item.dart [hunk 10]
```diff
@@ -1,41 +1,188 @@
...
+    AttachmentType attachmentType,
+    AttachmentMediaState mediaState,
+  ) async {
+    // Open attachment link
+    if (attachmentType == AttachmentType.link) {
+      openLink(attachment.link() ?? '', context);
+    }
+
+    // If attachment is media then check media is downloaded
+    else if (mediaState.mediaFile == null) {
```
Comment (gnunicorn) [inline app/lib/features/attachments/widgets/attachment_item.dart:141]: let's keep if and else together pls
```suggestion
    } else if (mediaState.mediaFile == null) {
    // If attachment is media then check media is downloaded
```

File: app/lib/features/attachments/widgets/attachment_section.dart [hunk 11]
```diff
@@ -122,146 +80,76 @@ class FoundAttachmentSectionWidget extends ConsumerWidget {
...
+          if (list.isEmpty) ...[
+            const SizedBox(height: 10),
+            Text(L10n.of(context).attachmentEmptyStateTitle),
+          ],
+          Wrap(
+            spacing: 5.0,
+            runSpacing: 10.0,
+            children: <Widget>[
+              if (list.isNotEmpty)
+                for (var item in list)
```
Comment (gnunicorn) [inline app/lib/features/attachments/widgets/attachment_section.dart:104]:
```suggestion
                for (var item in list)
```

unnecessary.

if at all it makes sense to put the entire `Wrap` behind the if ...

File: app/lib/features/pins/actions/attachment_leading_icon.dart [hunk 12]
```diff
@@ -0,0 +1,20 @@
...
+      return const Icon(Atlas.image_gallery);
+    case AttachmentType.video:
+      return const Icon(Atlas.video_camera);
+    case AttachmentType.audio:
+      return const Icon(Atlas.audio_headphones);
+    case AttachmentType.file:
+      return const Icon(Atlas.file);
+    default:
+      return const SizedBox.shrink();
+  }
```
Comment (gnunicorn) [inline app/lib/features/pins/actions/attachment_leading_icon.dart:19]: [new switch expression](https://dart.dev/language/branches#switch-expressions)?

```suggestion
  return switch (pinAttachmentType) {
    AttachmentType.link => const Icon(Atlas.link),
    AttachmentType.image => const Icon(Atlas.image_gallery),
    // ...
```

File: app/lib/features/pins/actions/select_pin_attachments.dart [hunk 13]
```diff
@@ -0,0 +1,58 @@
...
+import 'package:acter/features/pins/providers/pins_provider.dart';
+import 'package:file_picker/file_picker.dart';
+import 'package:flutter/material.dart';
+import 'package:flutter_riverpod/flutter_riverpod.dart';
+import 'package:logging/logging.dart';
+
+final _log = Logger('a3::pins::select::attachment');
+
+FileType attachmentFileType(AttachmentType pinAttachmentType) {
+  switch (pinAttachmentType) {
```
Comment (gnunicorn) [inline app/lib/features/pins/actions/select_pin_attachments.dart:14]: [new switch expression](https://dart.dev/language/branches#switch-expressions) ?

File: app/lib/features/pins/actions/select_pin_attachments.dart [hunk 14]
```diff
@@ -0,0 +1,58 @@
...
+//Select Attachment
+Future<void> selectAttachment(
+  WidgetRef ref,
+  AttachmentType attachmentType,
+) async {
+  try {
+    final fileType = attachmentFileType(attachmentType);
+    FilePickerResult? result = await FilePicker.platform.pickFiles(
+      type: fileType,
+      allowedExtensions: fileType == FileType.custom ? ['pdf', 'txt'] : null,
```
Comment (gnunicorn) [inline app/lib/features/pins/actions/select_pin_attachments.dart:37]: did we limit the extensions before as well? I don't think we want to do that or should do that ...

File: app/lib/features/pins/actions/select_pin_attachments.dart [hunk 15]
```diff
@@ -0,0 +1,58 @@
...
+        title: title,
+        fileExtension: fileExtension,
+        path: file.path,
+        size: fileSize,
+      );
+      ref.read(createPinStateProvider.notifier).addAttachment(attachment);
+    }
+  } catch (e, st) {
+    debugPrint('Error => $e');
+    _log.severe('Error => $e', st);
```
Comment (gnunicorn) [inline app/lib/features/pins/actions/select_pin_attachments.dart:56]: let's be more explicit
```suggestion
    _log.severe('Error selecting attachment',e, st);
```

File: app/lib/features/pins/models/create_pin_state/pin_attachment_model.dart [hunk 16]
```diff
@@ -0,0 +1,36 @@
+import 'package:acter/common/models/types.dart';
+
+class PinAttachment {
```
Comment (gnunicorn) [inline app/lib/features/pins/models/create_pin_state/pin_attachment_model.dart:3]: does that have to be bound to pin? shouldn't this be in the `attachment`s-features and something that can be reused for different cases?

File: app/lib/features/pins/providers/notifiers/create_pin_notifier.dart [hunk 17]
```diff
@@ -0,0 +1,45 @@
+import 'package:acter/features/pins/models/create_pin_state/create_pin_state.dart';
+import 'package:acter/features/pins/models/create_pin_state/pin_attachment_model.dart';
+import 'package:flutter_riverpod/flutter_riverpod.dart';
+
+class CreatePinNotifier extends StateNotifier<CreatePinState> {
+  final Ref ref;
+
+  CreatePinNotifier({required this.ref}) : super(const CreatePinState());
```
Comment (gnunicorn) [inline app/lib/features/pins/providers/notifiers/create_pin_notifier.dart:8]: why are you requesting ref? You don't need ref.

File: app/lib/features/pins/providers/pins_provider.dart [hunk 18]
```diff
@@ -37,3 +39,9 @@ final pinEditProvider = StateNotifierProvider.family
     .autoDispose<PinEditNotifier, PinEditState, ActerPin>(
   (ref, pin) => PinEditNotifier(pin: pin, ref: ref),
 );
+
+// Create Pin State
+final createPinStateProvider =
+    StateNotifierProvider.autoDispose<CreatePinNotifier, CreatePinState>(
+  (ref) => CreatePinNotifier(ref: ref),
```
Comment (gnunicorn) [inline app/lib/features/pins/providers/pins_provider.dart:46]:
```suggestion
  (ref) => CreatePinNotifier(),
```

File: app/lib/features/pins/widgets/pin_attachment_options.dart [hunk 19]
```diff
@@ -0,0 +1,144 @@
...
+  Widget _buildPinAttachmentOptions(BuildContext context, WidgetRef ref) {
+    final pinState = ref.watch(createPinStateProvider);
+    return Column(
+      children: [
+        Row(
+          mainAxisAlignment: MainAxisAlignment.spaceAround,
+          children: [
+            _pinAttachmentOptionItem(
+              context: context,
+              title: 'Text',
```
Comment (gnunicorn) [inline app/lib/features/pins/widgets/pin_attachment_options.dart:31]: l10n!

File: app/lib/features/pins/widgets/pin_attachment_options.dart [hunk 20]
```diff
@@ -0,0 +1,144 @@
...
+                  htmlBodyDescription:
+                      pinState.pinDescriptionParams?.htmlBodyDescription,
+                  plainDescription:
+                      pinState.pinDescriptionParams?.plainDescription,
+                );
+              },
+            ),
+            _pinAttachmentOptionItem(
+              context: context,
+              title: 'Link',
```
Comment (gnunicorn) [inline app/lib/features/pins/widgets/pin_attachment_options.dart:47]: l10n! ... and for all the ones following, too.

**Review by gnunicorn — APPROVED** [review]
One bug, and then some minor things. Merge as you see fit.

File: app/lib/features/pins/pages/create_pin.dart [hunk 21]
```diff
@@ -0,0 +1,359 @@
...
+        context: context,
+        ref: ref,
+        manager: manager,
+        attachments: attachment.path != null ? [File(attachment.path!)] : [],
+        title: attachment.title,
+        link: attachment.link,
+        attachmentType: attachment.attachmentType,
+      );
+    }
+  }
```
Comment (kumarpalsinh25) [inline app/lib/features/pins/pages/create_pin.dart:358]: This is the for loop which use to add all attachments with existing `handleAttachmentSelected`.

File: app/lib/features/attachments/actions/handle_selected_attachments.dart (hunk 6 above)
Comment (kumarpalsinh25) [reply app/lib/features/attachments/actions/handle_selected_attachments.dart:73]:
```
Future<void> handleAttachmentSelected({
  required BuildContext context,
  required WidgetRef ref,
  required AttachmentsManager manager,
  required List<File> attachments,
  String? title,
  String? link,
  required AttachmentType attachmentType,
})
```

This is the existing function I used to add all attachment [here](https://github.com/acterglobal/a3/pull/2048/files#r1715476655) with for loop.

In new, I used Pin State class where `PinAttachment` class I used for all attachment data including Link Type.

So for loop of `List<File> attachments, ` in `handleAttachmentSelected` doesn't match with new code.

I don't wanted to changes much in existing attachment module code so that's why handle it as it is but in later PRs I will optimised this function code.

File: app/lib/features/attachments/widgets/attachment_item.dart [hunk 22]
```diff
@@ -1,41 +1,152 @@
...
+import 'package:acter/features/pins/actions/attachment_leading_icon.dart';
 import 'package:acter_flutter_sdk/acter_flutter_sdk_ffi.dart' show Attachment;
+import 'package:atlas_icons/atlas_icons.dart';
 import 'package:flutter/material.dart';
+import 'package:flutter_gen/gen_l10n/l10n.dart';
 import 'package:flutter_riverpod/flutter_riverpod.dart';
+import 'package:share_plus/share_plus.dart';
 
 // Attachment item UI
 class AttachmentItem extends ConsumerWidget {
```
[the remark this answers is not in the document]
Comment (kumarpalsinh25) [reply app/lib/features/attachments/widgets/attachment_item.dart:19]: As this all about UI change and no side impact, I changed code attachment list code. So yes it change Attachment List UI for other also.

File: app/lib/common/utils/utils.dart [hunk 23]
```diff
@@ -36,6 +36,10 @@ final idMatrixRegexp = RegExp(
   r'matrix:roomid/(?<id>[^?]+)(\?via=(?<server_name>[^&]+))?(&via=(?<server_name2>[^&]+))?(&via=(?<server_name3>[^&]+))?',
 );
 
+final urlValidatorRegexp = RegExp(
```
[the remark this answers is not in the document]
Comment (kumarpalsinh25) [reply app/lib/common/utils/utils.dart:39]: I picked this from my person technical notes doc. From couple of years I am using this pattern but happy to change this if this doesn't satisfying our criteria.

File: app/lib/common/utils/utils.dart [hunk 24]
```diff
@@ -161,6 +165,34 @@ Future<bool> openLink(String target, BuildContext context) async {
   }
 }
 
+String getFileSize(int bytes) {
```
[the remark this answers is not in the document]
Comment (kumarpalsinh25) [reply app/lib/common/utils/utils.dart:168]: `renderFileSize` doesn't make sense to me as we aren't rendering anything from this function. Let me use `getHumanReadableFileSize`.

File: app/lib/features/attachments/actions/handle_selected_attachments.dart (hunk 6 above)
[the remark this answers is not in the document]
Comment (kumarpalsinh25) [reply app/lib/features/attachments/actions/handle_selected_attachments.dart:73]: As mentioned [here](https://github.com/acterglobal/a3/pull/2048#discussion_r1715487671),

This function still requires bit of improvement while I do further improvement in Add Attachment. So keeping it as it is now.

File: app/lib/features/attachments/widgets/attachment_item.dart (hunk 8 above)
Comment (kumarpalsinh25) [reply app/lib/features/attachments/widgets/attachment_item.dart:69]: Screenshot 2024-08-13 at 9 05 53 PM

I have added download button indication at trailing of the item. Later stage planning to add more option menu which can be useful for Edit and Delete option so afterward I will remove delete from long press.

---
- Long-press is ideal event for addition option for any UI item. So that putted delete over there till I come-up with better attachment list UI solution.

File: app/lib/features/attachments/widgets/attachment_item.dart (hunk 9 above)
Comment (kumarpalsinh25) [reply app/lib/features/attachments/widgets/attachment_item.dart:89]: `attachment.name()` want't giving me data somehow so used other way to handle it for temp. But yes this is not proper way and have this in my plan it use name() or relevant field. Right after this PR I am planning to fix this stuff.

File: app/lib/features/pins/actions/select_pin_attachments.dart (hunk 14 above)
Comment (kumarpalsinh25) [reply app/lib/features/pins/actions/select_pin_attachments.dart:37]: Nope, let me remove this restriction.

Comment (kumarpalsinh25) [reply app/lib/features/pins/actions/select_pin_attachments.dart:37]: I thought Image as File make sense in chat but doesn't make sense in Attachment View as there is already image selection available but let me remove it for now as there might be some thoughts arguments.

File: app/lib/features/pins/models/create_pin_state/pin_attachment_model.dart (hunk 16 above)
Comment (kumarpalsinh25) [reply app/lib/features/pins/models/create_pin_state/pin_attachment_model.dart:3]: Currently this is bound to Pin but yes in later PR it will be bound to attachment as common picker. Don't wanted to do attachment related additional changes in this PR.

File: app/lib/features/pins/providers/notifiers/create_pin_notifier.dart (hunk 17 above)
Comment (kumarpalsinh25) [reply app/lib/features/pins/providers/notifiers/create_pin_notifier.dart:8]: I was experimenting something and forgot to remove it. Good catch. Let me remove it.

**Comment by kumarpalsinh25** [comment]
@gnunicorn 

> One bug, 

Which bug?
I have address all your comments and did require changes in code/shared my answer.

Let me know if I missed anything which required to fix before merging this PR.
