### PR TITLE
Chat fixes

### LINKED ISSUE #1709: Chat fixes
high Priority 
 - [ ] #1732
- [ ] Preview is still shown of Acterglobla when mentioning user (pic 2), #1604
- [ ] Grey screen when mentioning user (pic3)

Lower:
- [ ] #1731
- [ ] When mentioning user, it also shows username, should only show display name (pic6)
- [ ] emoji icon white background? [#205](https://github.com/acterglobal/a3-meta/issues/205)

### PR DESCRIPTION
**Pull request by gnunicorn**
fixes #1709 .

Namely:
 - [x] Rework the mentioning of users by using the new `add_mentions` facilities provided by matrix and the rust SDK (for allowing to track mentions in encrypted chats as well)
 - [x] Fix the double naming problem in the mentions of a chat
 - [x] show the user drawer for mentioned users. 
 - [x] Fix the mentions overlay issue
 - [x] Fix the wrong color in selected reactions

See it in action:

https://github.com/acterglobal/a3/assets/40496/634bd99d-c270-447d-9bb8-7d3fb69f930f

### CODE REVIEW

File: native/core/src/events/attachments.rs [hunk 1]
```diff
@@ -92,6 +92,21 @@ pub enum AttachmentContent {
     Fallback(FallbackAttachmentContent),
 }
 
+impl TryFrom<MessageType> for AttachmentContent {
```
Comment (gtalha07) [inline native/core/src/events/attachments.rs:95]: Great code reduction!!! 👍🏻

**Review by gtalha07 — APPROVED** [review]
LGTM!
