### PR TITLE
Onboarding refactor with crash analytics & simplified screens

### LINKED ISSUE #1946: Startup Screens doesn't show next buttons some times
Especially found on windows:

Image

### PR DESCRIPTION
**Pull request by gnunicorn**
1. Refactors the "onboarding" folder into the separate components of "intro" (before anything), "auth" (everything authentication) and "onboarding" (the screens after registration/login). It also removes the in-between intro-screens that were mostly skipped and trims down a bit on the sizing of things so it works for smaller screens as well. Fixes #1946 . Test are updated accordingly.

https://github.com/user-attachments/assets/21f47502-776f-4ed8-97dc-4e1199ed626d

2. This adds support for Sentry Crash analytics. This is enabled by default in Nightly builds and off in any other. After login and as the last step in the registration onboarding, we are prompting the user whether we can do automatic crash analytics with sentry. On nightly this is active by default, for others this is off. We also have the option to add click-tracking later as well, there is still space on the page. Either way, the code is written in a way that if the user didn't accept this, we are not sending anything (which was a bit tricky as this isn't how the sentry-api is expected to work.). refs #576 .

After login:

https://github.com/user-attachments/assets/4029e6e4-8c86-4040-bcd0-b887150db56b

Oh, and the user can always turn it on/off in the settings -> info (as shown above).

After registration:

https://github.com/user-attachments/assets/64a7fe61-60aa-4f2f-9cc3-00f443fdd79c

### CODE REVIEW

File: app/lib/common/utils/routes.dart [hunk 1]
```diff
@@ -5,16 +5,20 @@ enum Routes {
...
+  // --- Auth
   authLogin('/login'),
   forgotPassword('/forgotPassword'),
   authRegister('/register'),
+
+  // -- onboarding
   saveUsername('/saveUsername'),
   linkEmail('/linkEmail'),
   uploadAvatar('/uploadAvatar'),
+  analyticsOptIn('/analyticsOptIn'),
```
Comment (kumarpalsinh25) [inline app/lib/common/utils/routes.dart:21]: Very nice!

**Review by kumarpalsinh25 — APPROVED** [review]
Much needed feature addition!

PR Code: 
Everything align pretty well! Great Job!
