### PR TITLE
Several chat state related fixes

### LINKED ISSUE #820: Chat: check permissions to sent
Currently room permissions are missing for members which would present the room UI in different ways. Like ability to post events, encryption status, power level. 
Screenshot 2023-08-02 at 10 01 01 PM

### LINKED ISSUE #1562: Disallow edition in permission-lack chat room
Our app should be modified so that user can't enter text in permission-lack chat room.
image

### LINKED ISSUE #1642: Reply state stays open
When I reply to a message and press send, the reply box stays open. Also I seem to be able to slide-to-edit on messages that I can't actually edit ....

https://github.com/acterglobal/a3/assets/40496/c558e997-9684-4dd1-a4f6-1685c09b6acd

### PR DESCRIPTION
**Pull request by gnunicorn**
Fixes several smaller chat input state related fixes. Each commit has a distinct fix attached.

Most notably:
- b1a4f5b2e4138039ec40742e13a16890185ff721 & 6fc0f76e206c36bb7bf4bf3f4017e37528769642 fixes #1642 
- 7c5cbf8b04ed9f110da52acb38fb90c72d8e2ffd fixes #1562, fixes #820 

Here is what that looks like now:

https://github.com/acterglobal/a3/assets/40496/eb862d99-713f-4454-9847-d6a29da5aa5c

And the blocked chat looks like this:

https://github.com/acterglobal/a3/assets/40496/9a834b25-3c42-47f4-8974-ec9ba518afc6

### CODE REVIEW

File: app/lib/features/chat/widgets/custom_input.dart [hunk 1]
```diff
@@ -48,17 +48,82 @@ final _allowEdit = StateProvider.family<bool, String>(
   ),
 );
 
-class CustomChatInput extends ConsumerStatefulWidget {
```
Comment (gtalha07) [inline app/lib/features/chat/widgets/custom_input.dart:51]: 👍🏻!

**Review by gtalha07 — APPROVED** [review]
LGTM! Only left is to add changelogs before merge ;)
