### PR TITLE
[Chat NG]: fix editor auto-scroll

### LINKED ISSUE #2564: chat-ng editor: third line disappears
As shown in the video, on desktop, writing beyond the second line, the cursor and all information just disappears. I can up to find the cursor again and can navigate down, but I never get to see the content.

https://github.com/user-attachments/assets/4c7c1e04-acc1-41f4-b502-cf7d08e83631

### PR DESCRIPTION
**Pull request by gtalha07**
- Fixes problematic ```shrinkwrap``` and ```disableAutoscroll``` properties along with some improvements in editor height to check for compatible area of scrolling as if not, seems to generate exceptions on appflowy side:
```
[2025-04-15][16:10:15.900570][a3::home::client_notifier][ERROR] platform dispatch error 'package:appflowy_editor/src/flutter/scrollable_helpers.dart': Failed assertion: line 236 pos 7: 'globalRect.size.width >= _dragTargetRelatedToScrollOrigin.size.width &&
          globalRect.size.height >=
              _dragTargetRelatedToScrollOrigin.size.height': Drag target size is larger than scrollable size, which may cause bouncing null #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:63:4)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:45:5)
errors_patch.dart:45
#2      EdgeDraggingAutoScroller._scroll (package:appflowy_editor/src/flutter/scrollable_helpers.dart:236:7)
scrollable_helpers.dart:236
#3      EdgeDraggingAutoScroller.startAutoScrollIfNecessary (package:appflowy_editor/src/flutter/scrollable_helpers.dart:215:5)
scrollable_helpers.dart:215
#4      AutoScroller.startAutoScroll (package:appflowy_editor/src/editor/editor_component/service/scroll/auto_scroller.dart:48:5)
auto_scroller.dart:48
#5      _DesktopScrollServiceState.startAutoScroll (package:appflowy_editor/src/editor/editor_component/service/scroll/desktop_scroll_service.dart:107:19)
desktop_scroll_service.dart:107
```
Resolves #2564.

Screenshot:

https://github.com/user-attachments/assets/a28636f4-a02a-42c4-9849-4de0115f56fc

## After [ea74b71](https://github.com/acterglobal/a3/pull/2837/commits/ea74b71c7b7457805b6e69f438704d964c4a52e8):

**improvements in height adjustments and smoothen auto-scrolling effect**:

https://github.com/user-attachments/assets/b9e94609-1da5-45d2-a5ad-4395edff662b

### CODE REVIEW

File: app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart [hunk 1]
```diff
@@ -278,62 +314,57 @@ class _ChatEditorState extends ConsumerState<ChatEditor> {
...
+
+    final needsScrolling = _needsScrolling(contentText);
+
+    return HtmlEditor(
+      footer: null,
+      // if provided, will activate mentions
+      roomId: widget.roomId,
+      hintText: hintText,
+      editable: true,
+      shrinkWrap: needsScrolling,
```
Comment (gtalha07) [inline app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart:356]: these two properties are source of fix, whereby we need to check whether scroll-able area is greater enough to enable auto scroll.

File: app/pubspec.yaml [hunk 2]
```diff
@@ -61,7 +61,7 @@ dependencies:
       ref: main
 
   flutter_easyloading: ^3.0.5
-  appflowy_editor: ^4.0.0
+  appflowy_editor: ^5.1.0
```
Comment (gtalha07) [inline app/pubspec.yaml:64]: also to upgrade dependencies before for improvements!

File: app/lib/common/widgets/html_editor/html_editor.dart [hunk 3]
```diff
@@ -426,15 +428,15 @@ class HtmlEditorState extends State<HtmlEditor> {
         linkItem,
         buildHighlightColorItem(),
       ],
-      textDirection: _textDirection,
+      textDirection: Directionality.of(context),
```
Comment (kumarpalsinh25) [inline app/lib/common/widgets/html_editor/html_editor.dart:431]: Very nice change as `Directionality` better handling of `ltr` and `rtl` directions instead of statically using fixed direction.

File: app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart [hunk 4]
```diff
@@ -40,27 +41,27 @@ class ChatEditor extends ConsumerStatefulWidget {
...
-      _updateHeight();
+
+      _updateContentHeight();
     });
-    // have it call the first time to adjust height
-    _updateHeight();
+
+    // Initialize the empty state correctly
+    _isInputEmptyNotifier.value = true;
+    _contentHeightNotifier.value = 64.0;
```
Comment (kumarpalsinh25) [inline app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart:63]: Not understanding why 
```
_isInputEmptyNotifier.value = true;
 _contentHeightNotifier.value = 64.0;
```
Set after `_updateContentHeight` Listener. Isn't it be before that?

File: app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart [hunk 5]
```diff
@@ -196,6 +189,30 @@ class _ChatEditorState extends ConsumerState<ChatEditor> {
...
+    height += (lineCount - 1) * 22.0;
+    return height;
+  }
+
+  void _updateContentHeight() {
+    final text = textEditorState.intoMarkdown();
+    double newHeight = _contentHeight(text);
+    newHeight = min(newHeight, 200.0);
+    if (_contentHeightNotifier.value != newHeight) {
+      _contentHeightNotifier.value = newHeight;
```
Comment (kumarpalsinh25) [inline app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart:215]: Not understanding this logic so skipping review of this.

File: app/lib/common/widgets/html_editor/html_editor.dart [hunk 6]
```diff
@@ -298,9 +300,9 @@ class HtmlEditor extends StatefulWidget {
 class HtmlEditorState extends State<HtmlEditor> {
   late EditorState editorState;
   late EditorScrollController editorScrollController;
-  final TextDirection _textDirection = TextDirection.ltr;
+
   // we store this to the stream stays alive
-  StreamSubscription<(TransactionTime, Transaction)>? _changeListener;
+  StreamSubscription<EditorTransactionValue>? _changeListener;
```
Comment (kumarpalsinh25) [inline app/lib/common/widgets/html_editor/html_editor.dart:305]: Not understanding what is `<EditorTransactionValue>` and why it is replace from `<(TransactionTime, Transaction)>?`

**Review by kumarpalsinh25 — COMMENTED** [review]
I am not able to understand the core logical changes so I can't make any decision to approve/reject PR.

However I am seeing the PR video that when user types with multiple lines, editor content updates with Jerky behaviour.

File: app/pubspec.yaml (hunk 2 above)
Comment (gnunicorn) [reply app/pubspec.yaml:64]: yay \o/

**Review by gnunicorn — APPROVED** [review]
@kumarpalsinh25 I think at this point neither of us can really confirm the validity in detail ... but maybe we can add some (golden) tests for things like these? I think that's the best way forward to also making sure we don't regress on these.

**Comment by gnunicorn** [comment]
@gtalha07 there is a visible size jump in the video when the editor gains focus, did you notice? Maybe that `64` is too large?

File: app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart (hunk 4 above)
Comment (gtalha07) [reply app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart:63]: Oh as now I'm thinking of it, this isn't needed. Let me remove it!

File: app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart (hunk 5 above)
Comment (gtalha07) [reply app/lib/features/chat_ng/widgets/chat_editor/chat_editor.dart:215]: Just as before code for dynamic expansion of field as user types multi-line, but this time taking care of auto-scrolling not get interfered by having enough area for editor.

File: app/lib/common/widgets/html_editor/html_editor.dart (hunk 6 above)
Comment (gtalha07) [reply app/lib/common/widgets/html_editor/html_editor.dart:305]: This comes after update of ```appflowy_editor``` to latest version. Newer API!

**Comment by gtalha07** [comment]
> @gtalha07 there is a visible size jump in the video when the editor gains focus, did you notice? Maybe that `64` is too large?

So yes, that is indeed a case. Having `64` has one reason that it the cursor jumps to next large with whole editor area large enough as to not generate inner editor exception for auto-scrolling. 

@kumarpalsinh25 Also about the jankiness of it which comes because of large shift of cursor, I don't think as of now if there's better way to resolve .i.e. I already reached discord community about this but let's see if they answer.
