### PR TITLE
fix convo card trailing

### LINKED ISSUE #2231: Missing time of latest message in chat rooms list view
Nothing shown anymore on the right side :(

### PR DESCRIPTION
**Pull request by gtalha07**
Fixes #2231. Bug fix include adding fallback ```trailing``` widget renderer as ```trailing``` param isn't passed in any call. That's why the message timestamp was missing from chat list.

### CODE REVIEW

File: app/lib/features/chat/widgets/convo_card.dart [hunk 1]
```diff
@@ -84,7 +84,9 @@ class ConvoCard extends ConsumerWidget {
                         overflow: TextOverflow.ellipsis,
                       ),
                 subtitle: buildSubtitle(context, constraints),
-                trailing: constraints.maxWidth < 300 ? null : trailing,
+                trailing: constraints.maxWidth < 300
```
Comment (kumarpalsinh25) [inline app/lib/features/chat/widgets/convo_card.dart:87]: Didn't getting visual idea about issue point and resolution by this code change.

Can you elaborate more about this in PR Description?

Comment (gtalha07) [reply app/lib/features/chat/widgets/convo_card.dart:87]: Added description.

Comment (kumarpalsinh25) [reply app/lib/features/chat/widgets/convo_card.dart:87]: what is difference between `trailing`  & `_TrailingWidget(roomId: roomId)` ?

Comment (gtalha07) [reply app/lib/features/chat/widgets/convo_card.dart:87]: It serves as fallback if ```trailing``` param isn't provided.
