### PR TITLE
Dashboard/Overview and Calendar Event fixes

### LINKED ISSUE #944: Add "+" icon to "my spaces" header on home screen
As new users now automatically join a space (Acter.global + Sandbox) they no longer get prompted with the "create space" pop up. Thats why i think its important that we either 

1. add the + icon to "my spaces" header on home screen
2. or, make it more clear that the "my spaces" is clickable.

Personally i would go for nr.1 as it doesnt take up a lot of space and its the shortest click path

Image

If its not a big job, adding the + icon in the space menu on desktop (like element) would also make it easier for users to get started with creating their own space.

Image

### PR DESCRIPTION
**Pull request by gtalha07**
- fixes #944.
- See #800 tracking.

### CODE REVIEW

File: app/lib/features/events/pages/events_page.dart [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+            actions: [
+              IconButton(
+                icon: const Icon(Atlas.funnel_sort_thin),
+                onPressed: () {
+                  customMsgSnackbar(
+                    context,
+                    'Events filtering not yet implemented',
+                  );
+                },
+              ),
```
Comment (gnunicorn) [inline app/lib/features/events/pages/events_page.dart:43]: Let's remove /disable buttons without function ...
```suggestion
```

File: app/lib/features/search/widgets/quick_jump.dart [hunk 2]
```diff
@@ -76,8 +90,6 @@ class QuickJump extends ConsumerWidget {
                     icon: SvgPicture.asset(
                       'assets/images/tasks.svg',
                       semanticsLabel: 'tasks',
-                      width: 32,
-                      height: 32,
```
Comment (gnunicorn) [inline app/lib/features/search/widgets/quick_jump.dart:80]: that is too small now. Please revert his and the `iconSize: 48` above.
grafik

File: app/lib/features/search/widgets/quick_jump.dart [hunk 3]
```diff
@@ -56,12 +55,27 @@ class QuickJump extends ConsumerWidget {
                     onPressed: () {
                       navigateTo(route: Routes.pins);
                     },
-                    icon: const Icon(Atlas.pin_thin, size: 32),
+                    icon: const Icon(Atlas.pin_thin),
```
Comment (gnunicorn) [inline app/lib/features/search/widgets/quick_jump.dart:58]:
```suggestion
                    icon: const Icon(Atlas.pin_thin, size: 32),
```

Pretty sure the size was set on purpose because otherwise this icon is crammed into the circle, appearing to pierce it:

grafik

File: app/lib/features/search/widgets/quick_jump.dart [hunk 4]
```diff
@@ -98,11 +109,9 @@ class QuickJump extends ConsumerWidget {
               },
               icon: const Icon(
                 Atlas.chats_thin,
-                size: 32,
```
Comment (gnunicorn) [inline app/lib/features/search/widgets/quick_jump.dart:101]: If I am not mistaken that was smaller on purpose, too. As seen in the image above, it is just too large for the circle it is in...

File: app/lib/features/space/widgets/chats_card.dart [hunk 5]
```diff
@@ -15,59 +15,62 @@ class ChatsCard extends ConsumerWidget {
...
+                  'There are no chats in this space',
+                  style: Theme.of(context).textTheme.bodySmall,
+                );
+              }
+              return Column(
+                children: [
+                  ListView.builder(
+                    shrinkWrap: true,
+                    physics: const NeverScrollableScrollPhysics(),
+                    itemCount: chats.length > 3 ? 3 : chats.length,
```
Comment (gnunicorn) [inline app/lib/features/space/widgets/chats_card.dart:43]: how about?
```suggestion
                    itemCount: min(chats.length, 3), 
```

**Review by gnunicorn — APPROVED** [review]
thanks, mate. I have some UI fixes, but we can postpone them if necessary...

File: app/lib/features/pins/pages/pins_page.dart [hunk 6]
```diff
@@ -67,9 +71,10 @@ class PinsPage extends ConsumerWidget {
               }
               return SliverGrid.builder(
                 itemCount: pins.length,
-                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
+                gridDelegate:
+                    SliverGridDelegateWithFixedCrossAxisCountAndFixedHeight(
                   crossAxisCount: max(1, min(widthCount, minCount)),
-                  childAspectRatio: 6,
+                  height: MediaQuery.of(context).size.height * 0.1,
```
Comment (gnunicorn) [inline app/lib/features/pins/pages/pins_page.dart:77]: I think this causes some ugly design, now:

grafik

Comment (gtalha07) [reply app/lib/features/pins/pages/pins_page.dart:77]: Let me take a look at it and do quick fix!

Comment (gtalha07) [reply app/lib/features/pins/pages/pins_page.dart]: Increased the height of card to contain chip: ``` height: MediaQuery.of(context).size.height * 0.15,```
