### PR TITLE
fix fallback user avatar size

### LINKED ISSUE #930: Fallback Avatar of User too small
Register a new account and you'll find the default selected fallback-avatar is too small:

Image

### PR DESCRIPTION
**Pull request by gtalha07**
- fixes #930.
- hide user avatar in dashboard (desktop) since we have in navigation rail already.
Screenshot 2023-09-18 at 8 10 22 PM
Screenshot 2023-09-18 at 8 10 41 PM

### CODE REVIEW

File: app/lib/common/widgets/user_avatar.dart [hunk 1]
```diff
@@ -23,7 +23,7 @@ class UserAvatarWidget extends ConsumerWidget {
             ActerAvatar(
               mode: DisplayMode.User,
               uniqueId: client.userId().toString(),
-              size: size,
+              size: data.profile.hasAvatar() ? size : size * 2,
```
Comment (gnunicorn) [inline app/lib/common/widgets/user_avatar.dart:26]: it really feels like we have a bunch of place where we do this... like ... we should probably take a look at our package and figure out why that is a problem, rather than putting a conditional `size * 2` everywhere it is being used...

File: app/lib/features/home/pages/dashboard.dart [hunk 2]
```diff
@@ -138,14 +138,17 @@ class _DashboardState extends ConsumerState<Dashboard> {
...
                     ),
-                    child: Container(
-                      key: Keys.avatar,
-                      margin: const EdgeInsets.all(8),
-                      child: InkWell(
-                        onTap: () => context.pushNamed(Routes.myProfile.name),
-                        child: const UserAvatarWidget(size: 20),
-                      ),
-                    ),
+                    child: !isDesktop
```
Comment (gnunicorn) [inline app/lib/features/home/pages/dashboard.dart:141]: arguably this should depend on the width/whether the sidebar is available rather than it "being desktop", but sure, let's do this for now...

**Review by gnunicorn — APPROVED** [review]
neither of these fixes is the fully properly one, but will do for now.
