### PR TITLE
Chat ng member state events fix

### LINKED ISSUE #2558: Not able to highligh text on desktop when wanting to copy only some text

### LINKED ISSUE #2615: Chat-NG : Profile change event is not yet supported
Image

### PR DESCRIPTION
**Pull request by gtalha07**
- Fixes #2615, #2609, #2617.

Screenshot 2025-02-19 at 20 52 52

Screenshot 2025-02-19 at 20 53 26

Screenshot 2025-02-19 at 20 56 07

- Fixes #2558 partially.

Screenshot 2025-02-19 at 21 00 48

### CODE REVIEW

File: app/lib/features/chat_ng/widgets/events/member_update_event.dart [hunk 1]
```diff
@@ -63,4 +34,87 @@ class MemberUpdateEvent extends StatelessWidget {
...
+          'Joined' => isMe
+              ? lang.chatYouJoined
+              : firstName != null
+                  ? lang.chatJoinedDisplayName(firstName)
+                  : lang.chatJoinedUserId(senderId),
+          'Left' => isMe
+              ? lang.chatYouLeft
+              : firstName != null
+                  ? lang.chatUserLeft(firstName)
+                  : lang.chatUserLeft(senderId),
```
Comment (kumarpalsinh25) [inline app/lib/features/chat_ng/widgets/events/member_update_event.dart:75]:
```suggestion
              : lang.chatUserLeft(firstName ?? senderId),
```

Similar things can be applies to all the other use-cases.

**Review by kumarpalsinh25 — APPROVED** [review]
Changes looks good to me.
