### PR TITLE
[Chat-NG] fix typing indicator 

### LINKED ISSUE #2907: Typing Indicator Not working in chat room
https://github.com/user-attachments/assets/a5fe2986-a5c4-4205-b94e-2fd6d252cfe1

### PR DESCRIPTION
**Pull request by gtalha07**
- Only changes are refactoring of typing indicator structure, specifically around the provider and state updates. fixes #2907

https://github.com/user-attachments/assets/a5ec1ae8-abd1-4415-b2c8-a89069ee073d

### CODE REVIEW

**Review by kumarpalsinh25 — COMMENTED** [review]
Code point of view, everything seem to be fine.

What was the root cause of the issue which doesn't showing typing indictor?

**Review by kumarpalsinh25 — APPROVED** [review]

**Comment by gnunicorn** [comment]
@gtalha07 I can see a screen-wide refresh happening, flicker of all avatars, when the typing first shows up. Any idea where that comes from and anything we can do about it?

**Comment by gtalha07** [comment]
> Code point of view, everything seem to be fine.
> 
> What was the root cause which was causing typing indictor not showing issue?

I think it's probably the way it was laid out in widget tree before. Having ```ref.watch()``` in widget methods sometimes causes issues with reactive updates over riverpod side...

**Comment by gtalha07** [comment]
> @gtalha07 I can see a screen-wide refresh happening, flicker of all avatars, when the typing first shows up. Any idea where that comes from and anything we can do about it?

Yeah I'd guess it's ```memberAvatarInfoProvider``` getting frequent refreshes. Been used in chain of ```typingEventProvider```, let me check if I can do quick fix on it.

File: app/lib/common/widgets/typing_indicator.dart [hunk 1]
```diff
@@ -6,29 +8,38 @@ import 'package:flutter_riverpod/flutter_riverpod.dart';
...
+    final users = ref.watch(chatTypingEventProvider(roomId)).valueOrNull;
+    final userIds = users?.map((userId) => userId.toString()).toList() ?? [];
+    return userIds
+        .map(
+          (userId) => ref.watch(
+            memberAvatarInfoProvider((userId: userId, roomId: roomId)),
+          ),
+        )
+        .toList();
+  }
```
Comment (gnunicorn) [inline app/lib/common/widgets/typing_indicator.dart:41]: why this complexity if that isn't actually used (here)?

File: app/lib/common/widgets/typing_indicator.dart [hunk 2]
```diff
@@ -45,11 +56,15 @@ class TypingWidget extends StatelessWidget {
   }
 
   @override
-  Widget build(BuildContext context) {
+  Widget build(BuildContext context, WidgetRef ref) {
     final l10n = L10n.of(context);
+    final typingUsers = _getTypingUsers(ref);
     final text = _buildTypingText(typingUsers, l10n);
 
+    if (typingUsers.isEmpty) return const SizedBox.shrink();
```
Comment (gnunicorn) [inline app/lib/common/widgets/typing_indicator.dart:64]: I think this can be simplified, no?

```suggestion
    if (ref.watch(chatTypingEventProvider(roomId)).valueOrNull?.isNotEmpty != true) return const SizedBox.shrink();
    
    
    final text = _buildTypingText(typingUsers, l10n);
```

**Review by gnunicorn — APPROVED** [review]

File: app/lib/common/widgets/typing_indicator.dart (hunk 1 above)
Comment (gtalha07) [reply app/lib/common/widgets/typing_indicator.dart]: I've created separate high level providers to inject them directly where they are needed :)

**Comment by gtalha07** [comment]
> > @gtalha07 I can see a screen-wide refresh happening, flicker of all avatars, when the typing first shows up. Any idea where that comes from and anything we can do about it?
> 
> Yeah I'd guess it's `memberAvatarInfoProvider` getting frequent refreshes. Been used in chain of `typingEventProvider`, let me check if I can do quick fix on it.

 it does seem the problem resides elsewhere, I'll deal that separately and not adding too much complications here 👍🏻
