### PR TITLE
some ui bug fixes

### LINKED ISSUE #987: Clicking on members preview list in the space header, should direct to the member section

### LINKED ISSUE #1029: Sidesheet title covered by mobile-top-bar
Not sure how to detect, but on Android Pixel 6a the top-bar with the camera is covering part of the sidebar titles:

grafik

### LINKED ISSUE #1036: (spaces overview) Shell header actions overflowing on system status.
IMG_4041

### PR DESCRIPTION
**Pull request by gtalha07**
- [x] fix #987.
- [x] fix #1029.
- [x] fix #1036.

### CODE REVIEW

File: app/lib/common/widgets/side_sheet.dart [hunk 1]
```diff
@@ -56,6 +56,7 @@ class SideSheet extends StatelessWidget {
         margin: EdgeInsets.only(
           bottom: MediaQuery.of(context).viewInsets.bottom,
         ),
+        padding: const EdgeInsets.only(top: 12),
```
Comment (gnunicorn) [inline app/lib/common/widgets/side_sheet.dart:59]: maybe add a code comment so we understand why this is here?
```suggestion
        padding: const EdgeInsets.only(top: 12), // keep space to top bar to prevent us being covered by front-camera etc..
```

**Review by gnunicorn — APPROVED** [review]
