### PR TITLE
Fixes QuickJump and Desktop Navbar routing issues.

### LINKED ISSUE #1680: Main Nav doesn't work on desktop
the wrong item is selected and click doesn't do anything. Confirmed on MacOS and Linux (`main`):

https://github.com/acterglobal/a3/assets/40496/667bdef5-0616-4231-8127-1f7bf44af714

### PR DESCRIPTION
**Pull request by kumarpalsinh25**
fixes #1680 

https://github.com/acterglobal/a3/assets/51526480/961715c9-c5da-4c26-bd0a-7cc710a0412e

### CODE REVIEW

File: app/lib/features/search/widgets/quick_jump.dart [hunk 1]
```diff
@@ -153,6 +153,11 @@ class _QuickJumpState extends ConsumerState<QuickJump> {
     ];
   }
 
+  void routeTo(String name) {
+    if (context.canPop()) context.pop();
+    context.pushNamed(name);
+  }
+
```
Comment (gnunicorn) [inline app/lib/features/search/widgets/quick_jump.dart:160]: can we do this typed, please?

```suggestion
  void routeTo(Route route) {
    if (context.canPop()) context.pop();
    context.pushNamed(route.name);
  }

```

**Review by gnunicorn — APPROVED** [review]
just a minor type improvement. thanks heaps.
