### PR TITLE
Chat-ng: fix room state events

### LINKED ISSUE #1907: Chat : Notice type messages aren't displayed
https://github.com/acterglobal/a3/assets/51526480/96ef3430-93c0-4522-af69-554a0a688055

### LINKED ISSUE #2616: Chat-NG : Many of the event just showing username, doesn't contains actual event related wordings.
Image

### PR DESCRIPTION
**Pull request by gtalha07**
### Fixes #2616, #2618: Adds missing room state events descriptive details:

Screenshot 2025-03-04 at 17 38 29

Screenshot 2025-03-04 at 17 40 57

Screenshot 2025-03-04 at 17 41 40

### Fixes #1907: Notice and server notice messages are added over rust side in timeline.

Screenshot 2025-03-04 at 17 52 10

### CODE REVIEW

File: app/lib/features/chat_ng/widgets/events/text_message_event.dart [hunk 1]
```diff
@@ -90,7 +91,7 @@ class TextMessageEvent extends StatelessWidget {
     final textTheme = Theme.of(context).textTheme;
     final chatTheme = Theme.of(context).chatTheme;
     final colorScheme = Theme.of(context).colorScheme;
-    final body = content.formattedBody() ?? content.body();
+    final body = content.formattedBody() ?? md.markdownToHtml(content.body());
```
Comment (gtalha07) [inline app/lib/features/chat_ng/widgets/events/text_message_event.dart:94]: had to bring markdown utility to convert to html as ```flutter_matrix_html``` doesn't support markdown format.

**Review by kumarpalsinh25 — APPROVED** [review]
Flutter side changes looks good to me.

File: native/acter/src/api/message.rs [hunk 2]
```diff
@@ -291,10 +295,207 @@ impl RoomEventItem {
...
             }
+
             TimelineItemContent::OtherState(s) => {
                 info!("Edit event applies to a state event");
-                me.event_type(s.content().event_type().to_string());
+                let event_type = s.content().event_type().to_string();
+                me.event_type(event_type.clone());
+                if let AnyOtherFullStateEventContent::RoomName(c) = s.content() {
+                    if let FullStateEventContent::Original {
+                        content,
```
Comment (gnunicorn) [inline native/acter/src/api/message.rs:305]: you have a clippy lint suggestion here, you probably want to apply

File: native/acter/src/api/message.rs [hunk 3]
```diff
@@ -291,10 +295,207 @@ impl RoomEventItem {
...
+                        prev_content,
+                    } = c
+                    {
+                        let msg_content = match (&content.name, &prev_content) {
+                            (new, Some(prev)) => match &prev.name {
+                                Some(old) => MsgContent::from_text(format!("{old} -> {new}")),
```
Comment (gnunicorn) [inline native/acter/src/api/message.rs:311]: fine for now, but in the future we probably want to leave that to the UI to decide as on LTR this is probably incorrect notation ;) .

File: native/acter/src/api/message.rs [hunk 4]
```diff
@@ -291,10 +295,207 @@ impl RoomEventItem {
...
+                if let AnyOtherFullStateEventContent::RoomAvatar(c) = s.content() {
+                    if let FullStateEventContent::Original {
+                        content,
+                        prev_content,
+                    } = c
+                    {
+                        let msg_content = match (&content.url, &prev_content) {
+                            (Some(new), Some(prev)) => match &prev.url {
+                                Some(_old) => MsgContent::from_image(
+                                    "updated room avatar".to_string(),
```
Comment (gnunicorn) [inline native/acter/src/api/message.rs:346]: future: l10n support?!?

File: native/acter/src/api/message.rs [hunk 5]
```diff
@@ -291,10 +295,207 @@ impl RoomEventItem {
...
+
+                if let AnyOtherFullStateEventContent::RoomEncryption(c) = s.content() {
+                    if let FullStateEventContent::Original {
+                        content,
+                        prev_content,
+                    } = c
+                    {
+                        let msg_content = match (&content.algorithm, &prev_content) {
+                            (new, Some(prev)) => match &prev.algorithm {
+                                old => MsgContent::from_text(format!("{:?} → {:?}", old, new)),
```
Comment (gnunicorn) [inline native/acter/src/api/message.rs:474]: why use the debug notation here?
```suggestion
                                old => MsgContent::from_text(format!("{old} → {new}")),
```

File: native/acter/src/api/message.rs [hunk 6]
```diff
@@ -291,10 +295,207 @@ impl RoomEventItem {
...
+
+                if let AnyOtherFullStateEventContent::RoomGuestAccess(c) = s.content() {
+                    if let FullStateEventContent::Original {
+                        content,
+                        prev_content,
+                    } = c
+                    {
+                        let msg_content = match (&content.guest_access, &prev_content) {
+                            (new, Some(prev)) => match &prev.guest_access {
+                                old => MsgContent::from_text(format!("{:?} → {:?}", old, new)),
```
Comment (gnunicorn) [inline native/acter/src/api/message.rs:490]: same

**Comment by bitfriend** [comment]
@gtalha07 Appended the missing state change cases in https://github.com/acterglobal/a3/pull/2673/commits/936967a9ba9a7c3b4cb1f9c0d0915e5f1e800257.
It covers only rust side.
It may be needed to implement flutter side too.
- Implement the missed cases in `l10n`
- Implement the missed cases in `app/lib/features/chat_ng/widgets/events/room_update_event.dart`
