### PR TITLE
minor UI fixes

### LINKED ISSUE #1206: "other" chats avatars aren't loading
If we have further chats in a space, we aren't part of (yet), their avatar is stuck at "loading"

Image

### PR DESCRIPTION
**Pull request by gnunicorn**
on top of #1434 . Review that first. Probably best to review commit by commit after.

- [x] fix #1206 
     grafik
- [x] show the empty chats only when there are not chats
      grafik
- [x] fix select space icons:
      grafik

### CODE REVIEW

File: app/lib/common/providers/chat_providers.dart [hunk 1]
```diff
@@ -24,13 +25,17 @@ final chatProfileDataProvider =
...
+      return ProfileData(displayName.text(), avatar.data(), isDm: isDm);
+    }
+  } catch (e) {
+    debugPrint('Loading avatar for ${convo.getRoomIdStr()} failed: $e');
   }
-  final sdk = await ref.watch(sdkProvider.future);
-  final size = sdk.api.newThumbSize(48, 48);
-  final avatar = await profile.getAvatar(size);
-  return ProfileData(displayName.text(), avatar.data(), isDm: isDm);
+  return ProfileData(displayName.text(), null, isDm: isDm);
```
Comment (kumarpalsinh25) [inline app/lib/common/providers/chat_providers.dart]: Nice change 👏

File: app/lib/features/space/pages/chats_page.dart [hunk 2]
```diff
@@ -25,153 +26,184 @@ class SpaceChatsPage extends ConsumerWidget {
...
+
+  Widget renderFurther(BuildContext context, WidgetRef ref) {
+    return relatedProvider(ref).when(
+      data: (provider) =>
+          RiverPagedBuilder<Next?, SpaceHierarchyRoomInfo>.autoDispose(
+        firstPageKey: const Next(isStart: true),
+        provider: provider,
+        itemBuilder: (context, item, index) => ConvoHierarchyCard(space: item),
+        noItemsFoundIndicatorBuilder: (context, controller) =>
+            _renderEmpty(context, ref),
```
Comment (kumarpalsinh25) [inline app/lib/features/space/pages/chats_page.dart:181]: Just to confirm, `_renderEmpty` will show when there are no chat list which we have join as well as no related chat, correct?

**Review by kumarpalsinh25 — APPROVED** [review]
Everything looks pretty good. Great work!

File: app/lib/common/providers/chat_providers.dart [hunk 3]
```diff
@@ -24,13 +25,17 @@ final chatProfileDataProvider =
...
-    return ProfileData(displayName.text(), null, isDm: isDm);
+  try {
+    if (profile.hasAvatar()) {
+      final sdk = await ref.watch(sdkProvider.future);
+      final size = sdk.api.newThumbSize(48, 48);
+      final avatar = await profile.getAvatar(size);
+      return ProfileData(displayName.text(), avatar.data(), isDm: isDm);
+    }
+  } catch (e) {
+    debugPrint('Loading avatar for ${convo.getRoomIdStr()} failed: $e');
```
Comment (gtalha07) [inline app/lib/common/providers/chat_providers.dart]: I assume this'll be changed after logging PR merge?

File: app/lib/features/space/pages/chats_page.dart [hunk 4]
```diff
@@ -25,153 +26,184 @@ class SpaceChatsPage extends ConsumerWidget {
...
+      orElse: () => const SliverToBoxAdapter(child: SizedBox.shrink()),
+    );
+  }
+
+  Widget _renderEmpty(BuildContext context, WidgetRef ref) {
+    final chats = ref.watch(relatedChatsProvider(spaceIdOrAlias));
+
+    if ((chats.valueOrNull?.isNotEmpty ?? true)) {
+      // we are still loading or chats has been found locally
+      return Container();
```
Comment (gtalha07) [inline app/lib/features/space/pages/chats_page.dart:102]: Why not use ```const SizedBox()```?

**Review by gtalha07 — APPROVED** [review]
Much needed fixes, thanks! All is left to add changelogs and good to go! ;)

File: app/lib/features/space/pages/chats_page.dart (hunk 4 above)
Comment (gnunicorn) [reply app/lib/features/space/pages/chats_page.dart:102]: I saw @kumarpalsinh25 use this one and honestly don't know if there is any reason to prefer one of the other... Is there?

Comment (gtalha07) [reply app/lib/features/space/pages/chats_page.dart:102]: > I saw @kumarpalsinh25 use this one and honestly don't know if there is any reason to prefer one of the other... Is there?

Pretty sure, that might be overlooked. Flutter  recommends using ```const SizedBox()``` for empty UI instead of ```Container()```.

Comment (gnunicorn) [reply app/lib/features/space/pages/chats_page.dart:102]: @gtalha07 do you have a link/reference for that? I'd like to know more about it ...

**Comment by gnunicorn** [comment]
@gtalha07 thanks for the reminder :bell: . I added the change log entry as well :)

File: app/lib/features/space/pages/chats_page.dart (hunk 4 above)
Comment (gtalha07) [reply app/lib/features/space/pages/chats_page.dart:102]: > @gtalha07 do you have a link/reference for that? I'd like to learn more about it ...

Indeed, here are some sources which talks on the usage of ```Container``` vs SizedBox.
https://medium.com/@olasoji.od/flutter-widgets-sizedbox-vs-container-7d9cf3e566f7
https://stackoverflow.com/questions/57703182/flutter-container-vs-sizedbox-for-dummy-empty

> Both of these widgets will create an empty space with the specified width and height. The SizedBox.shrink constructor is useful when you want to create a zero-sized box, which can be useful for spacing or padding. The Container widget can also be used for empty space, but it provides more customization options such as color, margin, padding, and decoration.

> It's worth noting that SizedBox is generally recommended for creating empty space because it's more lightweight and performant than Container. However, Container can be a better choice if you need more customization options or if you're already using it for other purposes.

Comment (kumarpalsinh25) [reply app/lib/features/space/pages/chats_page.dart:102]: > I saw @kumarpalsinh25 use this one and honestly don't know if there is any reason to prefer one of the other... Is there?

@gnunicorn 
My bad habit! Not major difference but still I agree with @gtalha07 that SizedBox is good for empty placeholder use-case.
